spring:
  application:
    name: HelloMall
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hellomall?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&charcterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
